#add stages here 
stages:
  Data-Preparation:
    cmd: python src/stage_01_data_preparation.py
    deps:
    - src/stage_01_data_preparation.py
    - src/utils
    - xmldata/data.xml
    outs:
    - artifacts/prepared

 
  Featurization:     
    cmd: python src/stage_02_featurization.py
    deps:
    - src/stage_02_featurization.py
    - src/utils
    - artifacts/prepared
    outs:
    - artifacts/features 

  train:     
    cmd: python src/stage_03_train.py
    deps:
    - src/stage_02_featurization.py
    - src/utils
    - artifacts/features
    outs:
    - artifacts/model/model.pkl

  evaluate:
    cmd: python src/stage_04_evaluate.py
    deps:
    - src/stage_04_evaluate.py
    - src/utils
    - artifacts/features/test.pkl
    - artifacts/model/model.pkl
    metrics:
      - scores.json:
          cache: false #No storage in cache
    plots:
      - prc.json:
          cache: false #No storage in cache
          x: recall
          y: precision
      - roc.json:
          cache: false #No storage in cache
          x: fpr
          y: tpr
    
