# Project information
site_name: StackOverflow Tag Prediction
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Data-Preparation: stage1dataprep.md

site_author: Deepanshu Kaushik
site_description: >-
  StackOverflow tag prediction: Project Workflow and Description

# Repository
repo_name: StackOverflow-tag-prediction_DVC
repo_url: https://github.com/001DEEPANSHU/StackOverflow-tag-prediction_DVC

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - toc.integrate
    - navigation.top
  language: en
  icon: 
    repo: fontawesome/brands/github

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: indigo 
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: indigo
      accent: indigo    




extra:
  social:
    - icon: fontawesome/brands/github
      name: Deepanshu on Github
      link: https://github.com/001DEEPANSHU
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/deepanshu-kaushik-795567154/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/001DEEPANSHU/"  target="_blank" rel="noopener">Deepanshu Kaushik</a>

