# Project information
site_name: NLP_DVC_Project
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Data-Preparation: stage1dataprep.md

site_author: Deepanshu Kaushik
site_description: >-
  StackOverflow tag prediction: Project Workflow and Description

# Repository
repo_name: 001DEEPANSHU/NLP_DVC_Project
repo_url: https://github.com/001DEEPANSHU/NLP_DVC_Project

# Configuration
theme:
  name: readthedocs
  # features:
  #   - navigation.tabs
  #   - navigation.sections
  #   - toc.integrate
  #   - navigation.top
  # language: en
  # palette:
  #   - scheme: default
  #     toggle:
  #       icon: material/toggle-switch-off-outline 
  #       name: Switch to dark mode
  #     primary: teal
  #     accent: purple 
  #   - scheme: slate 
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode    
  #     primary: teal
  #     accent: lime    
  # # logo: 
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/001DEEPANSHU
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/deepanshu-kaushik-795567154/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/001DEEPANSHU/"  target="_blank" rel="noopener">Deepanshu Kaushik</a>