# This contains params to be used by the stages to train or predict
prepare:
  split: 0.3
  seed: 22s
  tag: <python>

featurize:
  max_features: 2800
  n_grams: 3

train:
  seed: 2022
  criterion: gini
  min_samples_split: 4
  n_est: 100
  min_split: 16
  n_jobs: 2
